name: bun-test
run-name: ${{ github.actor }} is running bun-test
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun -g lerna
      - run: bun install
      - run: lerna run test
