name: Tests
run-name: ${{ github.actor }} is running Tests for PR ${{ github.event.number }}
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Packages
        run: bun install
      - name: Run Tests
        run: bun run test
      - name: Run Lint
        run: bun run format
